#!/bin/bash

echo "🌊 DigitalOcean App Platform Deployment"
echo "======================================"

echo "📋 Deployment Steps:"
echo "1. Go to https://cloud.digitalocean.com/apps"
echo "2. Click 'Create App'"
echo "3. Connect GitHub repo: https://github.com/Raghunath2604/Zipit.git"
echo "4. Select branch: main"
echo "5. DigitalOcean auto-detects Dockerfile"
echo "6. Choose plan (Basic $5/month or trial credits)"
echo "7. Click 'Create Resources'"
echo ""
echo "⚙️ Configuration:"
echo "- Runtime: Docker"
echo "- Port: 8000 (auto-detected from Dockerfile)"
echo "- Health check: /health"
echo ""
echo "🚀 Your ZipIt MLOps platform will be live at:"
echo "https://your-app-name.ondigitalocean.app"
echo ""
echo "✅ All features included:"
echo "- User authentication"
echo "- Model monitoring"
echo "- Drift detection" 
echo "- AI assistant chat"
echo "- Code workspace IDE"