FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/training/ ./
COPY src/dashboard/ ./dashboard/

EXPOSE 8504

CMD ["streamlit", "run", "automl_studio.py", "--server.port=8504", "--server.address=0.0.0.0"]